version: '{build}'
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  server: https://www.myget.org/F/config-aws-parameter-store/api/v2/package
  api_key:
    secure: Suqgd79Mx6aCHHr3+iVkunFslGrHEd4pXhP1P8mwjF9yQVbCQphVEoQCxfX6gYA1
  skip_symbols: true
  on:
    branch: master
